plugins {
    id 'com.android.library'
}

group 'com.example.volume'
version '1.0-SNAPSHOT'

android {
    compileSdkVersion 34

    // Add namespace for AGP 8.0+
    namespace "com.example.volume"

    defaultConfig {
        minSdkVersion 16
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.1.0'
}
